steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://s2pnexus-backend-120737021520.us-central1.run.app/api/v1'
      - '-t'
      - 'us-central1-docker.pkg.dev/s2pnexus/s2pnexus-repo/frontend:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/s2pnexus/s2pnexus-repo/frontend:latest'
