"""Workflow Automation domain models for S2PNexus (Sprint 2 ADR Phase 2F).

A WorkflowDefinition describes an ordered list of steps (stored as JSON) that
can be attached to any business entity (a contract, requisition, sourcing
event, supplier request/registration, etc). Supported step types:

- "condition": branches to a different step based on a field in the
  instance's context, implementing the ADR's "Conditions" capability.
- "approval": creates one WorkflowTask per approver (parallel approvals),
  supports N-of-M thresholds via required_approvals, and supports escalation
  via escalate_after_hours/escalate_to. Implements "Actions", "Parallel
  Approvals", "Escalations", and "Human Tasks".
- "notification": creates a Notification for each recipient. Implements
  "Notifications".

WorkflowInstance tracks a running (or completed) execution of a definition
against a specific entity. WorkflowTask is the individual human task/approval
unit. Notification is a simple in-app notification, reusable by any domain.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.database import Base

if TYPE_CHECKING:
    from app.models.user import User

VALID_STEP_TYPES = {"condition", "approval", "notification"}
VALID_INSTANCE_STATUSES = {"in_progress", "completed", "rejected", "cancelled"}
VALID_TASK_STATUSES = {"pending", "approved", "rejected", "escalated", "cancelled"}


class WorkflowDefinition(Base):
    __tablename__ = "workflow_definitions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True, comment="e.g. contract, procurement_requisition, sourcing_event")
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    steps: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list, comment="Ordered list of step definitions")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_by: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    instances: Mapped[list["WorkflowInstance"]] = relationship("WorkflowInstance", back_populates="definition", lazy="selectin")


class WorkflowInstance(Base):
    __tablename__ = "workflow_instances"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    definition_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("workflow_definitions.id", ondelete="RESTRICT"), nullable=False, index=True)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), default="in_progress", nullable=False, index=True)
    current_step_index: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    context: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict, comment="Snapshot of entity fields used to evaluate conditions")
    started_by: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    definition: Mapped["WorkflowDefinition"] = relationship("WorkflowDefinition", back_populates="instances", lazy="selectin")
    tasks: Mapped[list["WorkflowTask"]] = relationship("WorkflowTask", back_populates="instance", cascade="all, delete-orphan", lazy="selectin")


class WorkflowTask(Base):
    """A human task generated by an approval step (one row per parallel approver)."""

    __tablename__ = "workflow_tasks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    instance_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False, index=True)
    step_index: Mapped[int] = mapped_column(Integer, nullable=False)
    step_name: Mapped[str] = mapped_column(String(255), nullable=False)
    assignee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False, index=True)
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    escalate_to: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    escalated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    comments: Mapped[str | None] = mapped_column(Text, nullable=True)
    completed_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    instance: Mapped["WorkflowInstance"] = relationship("WorkflowInstance", back_populates="tasks", lazy="selectin")
    assignee: Mapped["User"] = relationship("User", foreign_keys=[assignee_id], lazy="selectin")


class Notification(Base):
    """A lightweight in-app notification, usable by any domain (approvals,
    awards, obligation reminders, escalations, etc.)."""

    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    recipient_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    related_entity_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    related_entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    recipient: Mapped["User"] = relationship("User", lazy="selectin")
