"""Initial migration

Revision ID: 69f2a7d2e2c5
Revises: 
Create Date: 2026-07-21 16:41:08.000258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f2a7d2e2c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='User full name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='User active status'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Session title'),
    sa.Column('system_prompt', sa.String(length=5000), nullable=True, comment='System prompt for the session'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document category/type'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Storage path (local/S3)'),
    sa.Column('content', sa.Text(), nullable=True, comment='Extracted text content'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='Creator user ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Supplier name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Supplier description'),
    sa.Column('contact_email', sa.String(length=255), nullable=True, comment='Contact email'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='Contact phone'),
    sa.Column('address', sa.Text(), nullable=True, comment='Supplier address'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Website URL'),
    sa.Column('tax_id', sa.String(length=100), nullable=True, comment='Tax identification number'),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='Payment terms'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Default currency (ISO 4217)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='Creator user ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_suppliers_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Session ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Message role (user/assistant/system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Contract title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Contract description'),
    sa.Column('contract_number', sa.String(length=100), nullable=False, comment='Contract number'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Supplier ID'),
    sa.Column('contract_type', sa.String(length=50), nullable=False, comment='Contract type'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Contract status'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Contract start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Contract end date'),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Contract value'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency (ISO 4217)'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='Auto-renewal flag'),
    sa.Column('renewal_notice_days', sa.Integer(), nullable=False, comment='Renewal notice period (days)'),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True, comment='Terms and conditions'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='Creator user ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_contracts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_contracts_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_supplier_id'), 'contracts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_contracts_title'), 'contracts', ['title'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='Source document ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Chunk index in document'),
    sa.Column('chunk_text', sa.String(length=8000), nullable=False, comment='Text chunk content'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Embedding model name'),
    sa.Column('dimensions', sa.Integer(), nullable=False, comment='Vector dimensions'),
    sa.Column('vector', sa.String(length=10000), nullable=False, comment='Embedding vector (JSON serialized)'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of chunk text for deduplication'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_embeddings_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index(op.f('ix_embeddings_content_hash'), 'embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_embeddings_document_id'), 'embeddings', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_document_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_content_hash'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_contracts_title'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_supplier_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
